### ISSUE TITLE
Possible incorrect field decoding

### ISSUE THREAD

**Issue by bluntelk** [openskynetwork/java-adsb#13]
Hi There,

I have been looking over your OperationalStatusMsg.java and it looks like on line 77 you have a mistake

```java
capability_class_code = (msg[1]<<4)|(msg[2]&0xF0);
```
logically should be something like:
```java
capability_class_code = (msg[1]<<4)|(msg[2]&0xF0)>>4;
```
otherwise you will be overwriting the first 4 bits.

**Comment by openskynetwork** [comment]
Thanks! This bug only affected the very rare surface OperationalStatus messages. Fixed in 99d5b4308a2f7406db9be8b0ba8aa0231aa4e2ef
