### ISSUE TITLE
The "airspeed_available" field of AirspeedHeadingMsg is always unavailable 

### ISSUE THREAD

**Issue by yanghsu** [openskynetwork/java-adsb#15]
The "airspeed_available" variable is set to false in AirspeedHeadingMsg's constructor, and there is no chance for it to be true.

It can be fixed like this

		true_airspeed = (msg[3]&0x80)>0;
		airspeed = (short) (((msg[3]&0x7F)<<3 | msg[4]>>>5&0x07)-1);
		// if (airspeed == -1) airspeed_available = false;
		 airspeed_available = (airspeed != -1);    // new assignment
		if (msg_subtype == 4) airspeed<<=2;

Example :   For raw message  "8f7bf0039b07c99580c8001c358b", the airspeed should be 171 (decimal),and airspeed_available should be true.

**Comment by affitz** [comment]
Fixed in a7492a27f40cb6dd813abaa7fdeb43f56cb4acec per pull request from  @yanghsu
