### ISSUE TITLE
How to get latitude and longitude？

### ISSUE THREAD

**Issue by Aimn** [openskynetwork/java-adsb#30]
Dear 
My adsb data is "8D7802995881120AB1E64B000000"
My mode-s data is "05B90011FAB412"
My Position is null
 How to get latitude and longitude from adsb data or mode-s data?
Thanks!

**Comment by fixje** [comment]
`8D7802995881120AB1E64B000000` is indeed an ADS-B position report. To decode the actual position the CPR algorith needs at least two ADS-B position reports, one of type *odd* and one of type *even*.

`05B90011FAB412` looks like an ACAS message which cannot be used to decode the position.

To understand how it works, you coulud have a look at the [ExampleDecoder](https://github.com/openskynetwork/java-adsb/blob/master/src/main/java/org/opensky/example/ExampleDecoder.java)

**Comment by Aimn** [comment]
thanks
