### ISSUE TITLE
Equipment Class in ADS - B Data

### ISSUE THREAD

**Issue by faheem1302** [openskynetwork/java-adsb#35]
**Class**
A0 Minimum Interactive
Aircraft/Vehicle Lower transmit power and less sensitive receive than Class A1.
A1S/A1 Basic Interactive Aircraft Standard transmit power and more sensitive receiver. Class A1
implements Antenna Diversity (Note)
A2 Enhanced Interactive
Aircraft Standard transmit power and more sensitive receiver. Interface with
avionics source required for aircraft trajectory intent data. Antenna
Diversity (Note)
A3 Extended Interactive
Aircraft
More sensitive receiver. Interface with avionics source required for
aircraft trajectory intent data.
Antenna Diversity (Note)
Broadcast-Only Participant Systems (Class B)
B0 Aircraft Broadcast Only Transmit power may be matched to coverage needs. Nav data input
required.
B1S/B1 Aircraft Broadcast Only Transmit power may be matched to coverage needs. Nav data input
required. Class B1 implements Antenna Diversity (Note)
B2 Ground Vehicle
Broadcast Only Transmit power matched to surface coverage needs. High accuracy
Nav data input required.
B3 Fixed Obstacle Fixed coordinates. No Nav data input required. Collocation with
obstacle not required with appropriate broadcast coverage.
Ground Receive Systems (Class C)
C1 ATS En Route and
Terminal Area Operations Requires ATS certification and interface to ATS sensor fusion
system.
C2 ATS Parallel Runway and
Surface Operation Requires ATS certification and interface to ATS sensor fusion
system.
C3 Flight Following
Surveillance Does not require ATS interface.

Where to retrieve them

**Comment by fixje** [comment]
Could you please provide a reference to the underlying standards/specification document?

**Comment by fixje** [comment]
closing due to missing information
