### ISSUE TITLE
Version 0 position accuracy for ADS-B does not have NUCp values?

### ISSUE THREAD

**Issue by sstephans** [openskynetwork/java-adsb#38]
I'm not sure if this is a bug or intended behavior. I am looking at the docs here https://mode-s.org/decode/adsb/uncertainty.html and saw that for version 0, there should be values from 0-9 for `NUCp`, and that there are not valid values for `NIC` for that version, either. 

However, when I look at `AirbornePositionV0Msg`, it has a method `#getNIC` that returns the values 0-11 and seems to be based off the tables under version 1. There is also no method that's returning the `NUCp` values from the tables in those docs. 

Is this a bug and should it be fixed? If not, can you explain what's going on with the `NIC` values and version 0/why it's set up this way?

Thanks!

**Comment by fixje** [comment]
Sorry for the late response...

> However, when I look at AirbornePositionV0Msg, it has a method #getNIC that returns the values 0-11 and seems to be based off the tables under version 1

See 2.4.8.1.16 and Table 2-200 in DO-260B. The interpretation holds for version 1 _and above_

>  There is also no method that's returning the NUCp values from the tables in those docs.

Yes, NIC has replaced NUC, so we are not considering it anymore
