### ISSUE TITLE
Publish to the central maven repository

### ISSUE THREAD

**Issue by wiseman** [openskynetwork/java-adsb#7]
You should publish this to the central Maven repository.

**Comment by Huehnergott** [comment]
do it if you like to

**Comment by wnagele** [comment]
+1

No - this should be done by the owner of the library not just anybody. Doesn't have to be Maven central - but some published location would be great.

**Comment by wiseman** [comment]
Hello!  Just curious if you've thought about this more.  As @wnagle mentioned above, the person or organization responsible for the library should really be the one that publishes it.  Publishing is a way to promote easy use and reuse, and if you encourage other people to publish without doing it yourself, then the risk is that there will be multiple unofficial versions published, varying in unknown ways.  It seems better for there to be one, clearly official version.  It's not particularly hard to do, e.g. see https://blog.idrsolutions.com/2015/06/how-to-upload-your-java-artifact-to-maven-central/

**Comment by fixje** [comment]
You are right. We should do this ourselves and it makes things much easier for all users of the library. I'll take care of it.

**Comment by fixje** [comment]
libadsb is now available in the central maven repository:

```
<dependency>
  <groupId>org.opensky-network</groupId>
  <artifactId>libadsb</artifactId>
  <version>1.1</version>
</dependency>
```

**Comment by wiseman** [comment]
Awesome, thanks!
