### ISSUE TITLE
Feature request: decode byte arrays

### ISSUE THREAD

**Issue by wiseman** [openskynetwork/java-adsb#8]
It would be nice for efficiency if the basic interface to the decoder used byte arrays rather than hex strings, with a convenience method for converting hex strings to byte arrays or whatever.

**Comment by Huehnergott** [comment]
Feel free to branch it and do this improvement for yourself.

**Comment by openskynetwork** [comment]
We only need hex strings in the interface as we are getting the data this way from our receivers.
If you need byte arrays, feel free to fork!
